### ISSUE TITLE
Purge of unused mods from the modset

### ISSUE THREAD

**Issue by VanWeapon** [SOCOMD/MODS#15]
**Description:**

-   As part of the end of year shutdown of normal ops, the modset will be purged of unused or limiting mods to make way for newer and more interesting mods. 

**Affected Area:**

-   All/3rd party mods

**Additional information/screenshots:**

-   TBC

**Comment by Slatery** [comment]
While confirmation will be needed, the general plan will be to replace all of our CUP assets, Factions, and other outdated 3rd party mods with RHS, 3CB Factions, and 3CB Vehicles/Weapons.

This has become a feasable proposal with the updates of 3CB Factions that have essentially made it into a lite version of CUP, giving us the assets we want a a high quality, without too much bloat.

A rough estimate in size difference does not show a massive amount difference between the two, both coming in around 27/28GB (+/- 1GB)

**Comment by SpectreOfRohan** [comment]
Unless I'm missing something, combined RHS + 3CB is ~15gb. 
Combined CUP (excluding terrains because we have to keep that) is ~8gb.
??

**Comment by Slatery** [comment]
Yes, you're missing something, the 4 RHS modules comes to around 17GB, and 3cb factions is actually close to 9.2GB. CUP Units + Weapons + Vehicles comes to 24GB, adding in CFP, CPC and the other CUP dependant mods (mostly faction packs) and it's roughly equal to the ~26-27GB of RHS

**Comment by SpectreOfRohan** [comment]
Yeah wow you're right, the Workshop file-sizes are way off. Noted. 

What other mods can we replace with RHS/3CB assets?

**Comment by Slatery** [comment]
We can also get rid of AGE, It's a nice mod but we aren't really using it, and was added on the idea that we could have more modern RUSFOR gear.

**Comment by Slatery** [comment]
But we'd be getting rid of all the faction mods (CFP, CPC, VCOM Units). I'd like to also make some custom factions with the new assets in the factions pbo

**Comment by SpectreOfRohan** [comment]
And RH Pistols? :D

**Comment by Slatery** [comment]
Yes, we'll have to make a list of all the pbos that are going to be removed

**Comment by socomdBandit** [comment]
Couldn't find a better place to put it so will put in here. When we add in the Super Hornet mod want to restrict munition on it to whatever the mod comes + some vanilla and possibly some RHS munitions to stop the munitions list from being so big it becomes overwhelming

**Comment by SpectreOfRohan** [comment]
Pretty much done but I'd add that we can remove:

TAW - Let's just do view distance manually. 
Ryan' Zombies - Learn how to use Drongos you lazy pricks. Also, we used it a grand total of 1 time after adding Drongos. 
STUI - We don't use at least 50% of the mod

**Comment by Slatery** [comment]
Agree for Ryan's zombies, STUI we've already striped everything we don't use, and don't see anything wrong with keeping taw, is a nice QOL mod

**Comment by SpectreOfRohan** [comment]
K then let's swap it for one that actually works.
Atm it is more a Pain of Life than a Quality of Life. 
Fucks with Zeus ability to RC tremendously, noticeable frame freeze if someone changes theirs to a long distance, spews shit in the RPT, and resets itself every mission.

**Comment by ToxicSpare** [comment]
Agree with Spectre, either manually set it in own settings or find another mod that works better (CH view distance?)
