### ISSUE TITLE
SOLS Q-Store Changes

### ISSUE THREAD

**Issue by socomdBandit** [SOCOMD/MODS#16]
**Description:**

-   Add the ACWP RIS M4A5's to pilot/crewman kits, Add (MC-ADF) USP T-Shirt to all roles with the SOLS Tee

**Affected Area:**

-   Loadouts

**Additional information/screenshots:**

-   N/A

**Comment by socomdBandit** [comment]
Awaiting HQ's approval but suspect it'll be given the green light so have added it prematurely

**Comment by ToxicSpare** [comment]
Remove AUG if SOLS are getting the M4, then we can look at getting rid of SMA entirely when swapping to RHS

**Comment by socomdBandit** [comment]
@ToxicSpare rog, should i remove the CUP MP5 aswell since thats also going during the mod overhaul?

**Comment by ToxicSpare** [comment]
Replace with the vanilla mp5

**Comment by Slatery** [comment]
reference https://github.com/SOCOMD/MODS/commit/75267e428d1e0778e33917793ef497700d19645c#diff-6880152f2ba3af5d742845ff96510dff8a892f0847a1cc45335e15a2b269d6bd

**Comment by Slatery** [comment]
don't start doing refactor related things on the main branch

**Comment by socomdBandit** [comment]
so make this its own branch?

**Comment by socomdBandit** [comment]
too easy, Just had a look at some of the stuff in 75267e4 and have changes a few things around, will push to master so you can see what im on about
