### ISSUE TITLE
Restrict gun camo options based on map type

### ISSUE THREAD

**Issue by VanWeapon** [SOCOMD/MODS#18]
**Description:**

-   Rifle camouflage options for the primary weapon, (mainly talking about the M4A5) should be restricted based on map types. 
- Arid maps should not allow don/od
- Jungle/forest/swamp maps not allow tan

This should reduce the clutter of weapon customisation screen a bit 

**Affected Area:**

-   Loadouts/qstore

**Additional information/screenshots:**

-   There is already a system in place for restricting Uniform camouflage options based on map type, this could potentially be extended further to cover weapon choices as well
- There was also talk of implementing a new UI over the arsenal to allow selecting a base model rifle, then adding customisation options (grip/cam/barrel length etc) in a second UI. Depending on how feasible this second option is, we may decide to either proceed with the first option or just wait til we can implement the second.

**Comment by socomdBandit** [comment]
I know personally i just make my gun look cool rather than try and match the camo with the environment and i feel like many would share the same sentiment, would recommend getting player base feedback before implementing this

**Comment by Slatery** [comment]
I don't see any real benefit aside from reducing clutter from the QStore. Personally I'd prefer to just remove the camo'd variants of the black railed M4, since the difference between those and the tan rail is so miniscule

**Comment by VanWeapon** [comment]
For context, there are 114 M4A5 varients from the standard socomd qstore
Removing the black rail variants lowers it by 37, and removing 1 colour option per map type (e.g. remove don from arid maps) would reduce this by a further 33, cutting the total amount to pick from to half of what it is currently.

**Comment by Slatery** [comment]
Those numbers seem off. Given that there are 14 configuration variants for each camo between 10.5 and 14.5 (not including the 7" rail version) removing all 3 black rail+camo variants would be at least 42 removed. Removing a single camo ontop of that would at least lower it by only another 14, or at most between 21 and 27 (assuming 7x7" variants + 2 GL variants on some classes, and 4xHK 416s which don't have all the camos), to a total between 56 and 69 removed.

**Comment by VanWeapon** [comment]
The RIS versions dont have black rail variants, feel free to double check but I got those numbers from text matching using the naming conventions for the `GENERAL_RIFLE` define in `addons\loadouts\configs\arsenal_options\default.hpp`

**Comment by VanWeapon** [comment]
Semantics anyway, there's a lot and this is mainly about the clutter problem not necessarily the thematic one

**Comment by ToxicSpare** [comment]
I like the Don camo best, I don't run any other camo. Restricting that on arid maps does not allow me to play with my favourite camo. All of my loadouts are saved with Don or black camos. Removing these is just needless IMO.

**Comment by socomdBandit** [comment]
If QStore clutter is really an issue we could look into something for weapons like the system Van posted in J4 for the USP uniforms. If not id rather keep the clutter and be able to run whatever camo I felt like

**Comment by VanWeapon** [comment]
Agreed @socomdBandit, that would be my preference as well, as mentioned in #19 though, in order to do this requires a lot of extra config code on top of adding 2 extra mods to the modset
