### ISSUE TITLE
SOCOMD Zeus Module: "Show Hit Points" not functioning as intended

### ISSUE THREAD

**Issue by SpectreOfRohan** [SOCOMD/MODS#20]
**Description:**

-   Module applies without error, however, the RGB does not reflect damage taken on a Vehicle as code intends. A Vehicle remains "transparent white" regardless of damage taken. 

**Steps to reproduce:**

-   Load Zeus > Use Show Hit Points module on a Vehicle > Shoot at Vehicle in increments until it asplodies.

**Comment by NathanChambers** [comment]
This module doesn't reflect damage taken. It shows where the engine and fuel tank hit points are. Doesn't work on every vehicle.
