### ISSUE TITLE
**Medical Airways as "medic" are unviewable**

### ISSUE THREAD

**Issue by TeemoLover** [SOCOMD/MODS#24]
**Description:**

-   For anything outside the basic medical, airways are unviewable and aren't able to be used without "memorising" where they are.

**Steps to reproduce:**

-   possibly able to "readd" the wording back so we are able to know what we are "doing".

**Additional information:**

-   pls fix.

**Comment by VanWeapon** [comment]
Added screenshot 
![image](https://user-images.githubusercontent.com/30616047/136678548-11e7b998-cc7d-4361-8ceb-1f7638c118ed.png)
