### ISSUE TITLE
Various issues with Medical system

### ISSUE THREAD

**Issue by VanWeapon** [SOCOMD/MODS#32]
**Description:**

Various medical issues reported, possibly due to recent updates to KAT.
- SPO2 stays at 100 even when obstructed/occluded - requires further testing to confirm
- Reports of some people dying after a short time with airways obstructed (<30 secs from first down to KIA)
- Pneumo tools are visible in advanced treatments even when the patient has no Pneumos 

**Steps to reproduce:**

-   Observable in the above scenarios
- Quick deaths from airways is the result of multiple different airway injuries compounding each other and making the death timer approach quicker, e.g. each type of Pneumo, obstruction, occlusion, and no heart rate all add to the speed of the airway death timer. 

**Additional information:**

-   This is probably due to KAT updates, however SOCOMD maintains a fork of KAT where we can fix these bugs to work with our modset.
- As more bug reports are filed, will continue adding to the scenarios 
- [SOCOMD/KAM
](https://github.com/SOCOMD/KAM)

**Comment by SpectreOfRohan** [comment]
- Malformed blood texture occurring, so far on any map, from bleeding players: https://cdn.discordapp.com/attachments/898787416050110474/903593906359398440/unknown.png
