### ISSUE TITLE
@acwp mod does not update with Arma3Sync

### ISSUE THREAD

**Issue by VanWeapon** [SOCOMD/MODS#8]
**Description:**
- When using Arma3Sync to update the SOCOMD modset, the @acwp set remains red and notifies you constantly that it needs an update.

**Steps to reproduce:**
- Open A3Sync and attempt to download the latest mod updates
- Observe that @acwp remains red, indicating a file needs to be deleted, but A3Sync does not delete the file

**Additional information:**
- This issue can be resolved manually by going to your Arma 3 SOCOMD folder where the mods are located, and manually deleting the bisign file ref below screenshots. 
- The file will be redownloaded by A3Sync next time you sync the mod repo. 

![image](https://user-images.githubusercontent.com/30616047/135744082-90b81c14-2636-4d2c-8746-0ce06d7e3654.png)
![image](https://user-images.githubusercontent.com/30616047/135744083-e4cb9a72-65f6-49c2-bae3-3db19dd8302e.png)

**Comment by Slatery** [comment]
I believe as is inferred with the labels, that this is just an A3sync issue, and occurs with more than just that bisign, as was highlighted by CJ in the supprt channel on 21/09/21. I don't know of anything we can do outside of making our own mod updater
